#!/bin/sh

# We will permanently pin netdata to wokr on Core 0
#
# This modifies the init script so that ANY time netdata starts
# (manually or automatically), it stays on Core 0.
if [ -f /etc/init.d/netdata ]; then
    # Check if we haven't already patched it
    if ! grep -q "taskset" /etc/init.d/netdata; then
        # Inject taskset -c 0 before the binary execution
        # Core 0 is your OS/Generic core (per smp_affinity), keeping Netdata off NSS/WiFi cores.
        sed -i "s|procd_set_param command /usr/sbin/netdata|procd_set_param command /usr/bin/taskset -c 0 /usr/sbin/netdata|g" /etc/init.d/netdata
    fi
fi

exit 0