#!/bin/sh

if /usr/bin/is-default-config cpu-perf; then

    touch /etc/config/cpu-perf

    uci -q batch <<'EOF'
delete cpu-perf.config
set cpu-perf.ondemand=governor
set cpu-perf.conservative=governor
set cpu-perf.performance=governor
set cpu-perf.schedutil=governor
set cpu-perf.config=main
set cpu-perf.config.enabled='1'
set cpu-perf.cpu0=cpu
set cpu-perf.cpu0.scaling_governor='performance'
set cpu-perf.cpu1=cpu
set cpu-perf.cpu1.scaling_governor='performance'
set cpu-perf.cpu2=cpu
set cpu-perf.cpu2.scaling_governor='performance'
set cpu-perf.cpu3=cpu
set cpu-perf.cpu3.scaling_governor='performance'

commit cpu-perf
EOF

fi

exit 0
