#!/bin/sh

# The system ROM Config does not exist, it's generated on-demand, but if the
# config already exists, leave as it-is
if /usr/bin/is-default-config system && [ ! -f /etc/config/system ]; then

    touch /etc/config/system

    uci -q batch <<'EOF'
# System ROM does not exist, so we will just set the configuration
uci -q batch <<'EOF'
delete system.@system[0]
add system system
set system.@system[0]=system
set system.@system[0].hostname='OpenWrt_WRX36'
set system.@system[0].ttylogin='0'
set system.@system[0].log_size='64'
set system.@system[0].urandom_seed='0'
set system.@system[0].log_proto='udp'
set system.@system[0].conloglevel='8'
set system.@system[0].cronloglevel='5'
set system.@system[0].zram_comp_algo='zstd'
set system.@system[0].description='OpenWrt on Dynalink DL-WRX36 (NSS)'
set system.@system[0].notes='Custom NSS-enabled OpenWrt firmware for Dynalink DL-WRX36'

delete system.ntp
set system.ntp=timeserver
set system.ntp.enabled='0'

delete system.@rngd[0]
add system rngd
set system.@rngd[0]=rngd
set system.@rngd[0].enabled='1'
set system.@rngd[0].device='/dev/urandom'

commit system
EOF

fi

exit 0
