#!/bin/sh

# Add the it-tools configuration if it does not exists already.
if ! uci show uhttpd.it_tools 2>/dev/null; then

    uci -q batch <<'EOF'
set uhttpd.uhttpd=it_tools
add_list uhttpd.uhttpd.it_tools.listen_http='0.0.0.0:8080'
add_list uhttpd.uhttpd.it_tools.listen_http='[::]:8080'
set uhttpd.uhttpd.it_tools.redirect_https='0'
set uhttpd.uhttpd.it_tools.home='/www/tools/'
set uhttpd.uhttpd.it_tools.rfc1918_filter='1'
set uhttpd.uhttpd.server_name='it-tools.local'
set uhttpd.uhttpd.index_page='index.html'
set uhttpd.uhttpd.max_requests='3'
set uhttpd.uhttpd.max_connections='100'
EOF

fi

exit 0
