#!/bin/sh

if /usr/bin/is-default-config fstab; then

    touch /etc/config/fstab

    uci -q batch <<'EOF'
delete fstab.@global[0]
add fstab global
set fstab.@global[0]=global
set fstab.@global[0].anon_swap='0'
set fstab.@global[0].anon_mount='0'
set fstab.@global[0].auto_swap='1'
set fstab.@global[0].auto_mount='1'
set fstab.@global[0].delay_root='5'
set fstab.@global[0].check_fs='1'

delete fstab.@mount[0]
add fstab mount
set fstab.@mount[0]=mount
set fstab.@mount[0].enabled='0'
set fstab.@mount[0].label='CHANGE ME FOR THE PROPER TARGET'
set fstab.@mount[0].target='/mnt/sda1'

delete fstab.@mount[1]
add fstab mount
set fstab.@mount[1]=mount
set fstab.@mount[1].enabled='0'
set fstab.@mount[1].target='/tmp/plexmediaserver'
set fstab.@mount[1].fstype='squashfs'

delete fstab.@swap[0]
add fstab swap
set fstab.@swap[0]=swap
set fstab.@swap[0].enabled='1'
set fstab.@swap[0].device='/dev/zram0'

delete fstab.@uvol[0]
add fstab uvol
set fstab.@uvol[0]=uvol
set fstab.@uvol[0].initialized='1'

commit fstab
EOF

fi

exit 0
