#!/bin/sh

if /usr/bin/is-default-config usteer; then

    touch /etc/config/usteer

    uci -q batch <<'EOF'
delete usteer.@usteer[0]
add usteer usteer
set usteer.@usteer[0]=usteer
set usteer.@usteer[0].network='lan'
set usteer.@usteer[0].syslog='1'
set usteer.@usteer[0].local_mode='1'
set usteer.@usteer[0].ipv6='0'
set usteer.@usteer[0].debug_level='1'
set usteer.@usteer[0].band_steering_threshold='5'
set usteer.@usteer[0].band_steering_interval='10000'
set usteer.@usteer[0].band_steering_min_snr='-75'
set usteer.@usteer[0].signal_diff_threshold='5'
set usteer.@usteer[0].initial_connect_delay='1000'
set usteer.@usteer[0].ssid_list='OpenWrt_WiFi'

commit usteer
EOF

fi

exit 0
