#!/bin/sh

if /usr/bin/is-default-config firewall; then

    touch /etc/config/firewall

    uci -q batch <<'EOF'
delete firewall.@defaults[0]
add firewall defaults
set firewall.@defaults[0]=defaults
set firewall.@defaults[0].input='REJECT'
set firewall.@defaults[0].output='ACCEPT'
set firewall.@defaults[0].forward='REJECT'
set firewall.@defaults[0].syn_flood='1'

# LAN Zone
delete firewall.@zone[0]
add firewall zone
set firewall.@zone[0]=zone
set firewall.@zone[0].name='lan'
set firewall.@zone[0].input='ACCEPT'
set firewall.@zone[0].output='ACCEPT'
set firewall.@zone[0].forward='ACCEPT'
delete firewall.@zone[0].network
add_list firewall.@zone[0].network='lan'

delete firewall.@forwarding[0]
add firewall forwarding
set firewall.@forwarding[0]=forwarding
set firewall.@forwarding[0].src='lan'
set firewall.@forwarding[0].dest='wan'

# IoT Zone
delete firewall.@zone[1]
add firewall zone
set firewall.@zone[1]=zone
set firewall.@zone[1].name='IoT'
set firewall.@zone[1].input='REJECT'
set firewall.@zone[1].output='ACCEPT'
set firewall.@zone[1].forward='REJECT'
delete firewall.@zone[1].network
add_list firewall.@zone[1].network='IoT'

delete firewall.@forwarding[1]
add firewall forwarding
set firewall.@forwarding[1]=forwarding
set firewall.@forwarding[1].src='IoT'
set firewall.@forwarding[1].dest='wan'

# WAN Zone
delete firewall.@zone[2]
add firewall zone
set firewall.@zone[2]=zone
set firewall.@zone[2].name='wan'
delete firewall.@zone[2].network
add_list firewall.@zone[2].network='wan'
add_list firewall.@zone[2].network='wan6'
set firewall.@zone[2].input='REJECT'
set firewall.@zone[2].output='ACCEPT'
set firewall.@zone[2].forward='REJECT'
set firewall.@zone[2].masq='1'
set firewall.@zone[2].mtu_fix='1'

delete firewall.@forwarding[2]
add firewall forwarding
set firewall.@forwarding[2]=forwarding
set firewall.@forwarding[2].src='lan'
set firewall.@forwarding[2].dest='IoT'

# Tailscale Zone
delete firewall.@zone[3]
add firewall zone
set firewall.@zone[3]=zone
set firewall.@zone[3].name='tailscale'
delete firewall.@zone[3].network
add_list firewall.@zone[3].network='tailscale'
set firewall.@zone[3].input='ACCEPT'
set firewall.@zone[3].output='ACCEPT'
set firewall.@zone[3].forward='REJECT'
set firewall.@zone[3].masq='1'
set firewall.@zone[3].mtu_fix='1'
set firewall.@zone[3].masq6='1'

delete firewall.@forwarding[3]
add firewall forwarding
set firewall.@forwarding[3].src='tailscale'
set firewall.@forwarding[3].dest='lan'

delete firewall.@forwarding[4]
add firewall forwarding
set firewall.@forwarding[4].src='tailscale'
set firewall.@forwarding[4].dest='wan'

delete firewall.@forwarding[5]
add firewall forwarding
set firewall.@forwarding[5].src='lan'
set firewall.@forwarding[5].dest='tailscale'

# ZeroTier Zone
delete firewall.@zone[4]
add firewall zone
set firewall.@zone[4]=zone
set firewall.@zone[4].name='zerotier'
delete firewall.@zone[4].network
add_list firewall.@zone[4].network='zerotier'
set firewall.@zone[4].input='ACCEPT'
set firewall.@zone[4].output='ACCEPT'
set firewall.@zone[4].forward='ACCEPT'
set firewall.@zone[4].masq='1'

delete firewall.@forwarding[6]
add firewall forwarding
set firewall.@forwarding[6].src='zerotier'
set firewall.@forwarding[6].dest='lan'

delete firewall.@forwarding[7]
add firewall forwarding
set firewall.@forwarding[7].src='zerotier'
set firewall.@forwarding[7].dest='wan'

delete firewall.@forwarding[8]
add firewall forwarding
set firewall.@forwarding[8].src='lan'
set firewall.@forwarding[8].dest='zerotier'

# DNS redirection for Adblock
delete firewall.@redirect[0]
add firewall redirect
set firewall.@redirect[0]=redirect
set firewall.@redirect[0].name='Force-Adblock-Iot'
set firewall.@redirect[0].src='IoT'
add_list firewall.@redirect[0].proto='tcp'
add_list firewall.@redirect[0].proto='udp'
set firewall.@redirect[0].src_dport='53'
set firewall.@redirect[0].dest_port='53'
set firewall.@redirect[0].target='DNAT'
set firewall.@redirect[0].enabled='0'

delete firewall.@redirect[1]
add firewall redirect
set firewall.@redirect[1]=redirect
set firewall.@redirect[1].name='Force-Adblock-Lan'
set firewall.@redirect[1].src='lan'
add_list firewall.@redirect[1].proto='tcp'
add_list firewall.@redirect[1].proto='udp'
set firewall.@redirect[1].src_dport='53'
set firewall.@redirect[1].dest_port='53'
set firewall.@redirect[1].target='DNAT'
set firewall.@redirect[1].enabled='0'

# NSS offloading
delete firewall.qcanssecm
set firewall.qcanssecm=include
set firewall.qcanssecm.type='script'
set firewall.qcanssecm.path='/etc/firewall.d/qca-nss-ecm'

commit firewall
EOF

    /usr/bin/add-management-wan-to-firewall

fi

exit 0