#!/bin/sh

if /usr/bin/is-default-config firewall; then

    touch /etc/config/firewall

    uci -q batch <<'EOF'
delete firewall.@defaults[0]
add firewall defaults
set firewall.@defaults[0]=defaults
set firewall.@defaults[0].input='REJECT'
set firewall.@defaults[0].output='ACCEPT'
set firewall.@defaults[0].forward='REJECT'
set firewall.@defaults[0].syn_flood='1'

# LAN Zone
delete firewall.@zone[0]
add firewall zone
set firewall.@zone[0]=zone
set firewall.@zone[0].name='lan'
add_list firewall.@zone[0].network='lan'
set firewall.@zone[0].input='ACCEPT'
set firewall.@zone[0].output='ACCEPT'
set firewall.@zone[0].forward='ACCEPT'

delete firewall.@forwarding[0]
add firewall forwarding
set firewall.@forwarding[0]=forwarding
set firewall.@forwarding[0].src='lan'
set firewall.@forwarding[0].dest='wan'

# IoT Zone
delete firewall.@zone[1]
add firewall zone
set firewall.@zone[1]=zone
set firewall.@zone[1].name='IoT'
set firewall.@zone[1].input='REJECT'
set firewall.@zone[1].output='ACCEPT'
set firewall.@zone[1].forward='REJECT'
add_list firewall.@zone[1].network='IoT'

delete firewall.@forwarding[1]
add firewall forwarding
set firewall.@forwarding[1]=forwarding
set firewall.@forwarding[1].src='IoT'
set firewall.@forwarding[1].dest='wan'

# WAN Zone
delete firewall.@zone[2]
add firewall zone
set firewall.@zone[2]=zone
set firewall.@zone[2].name='wan'
add_list firewall.@zone[2].network='wan'
add_list firewall.@zone[2].network='wan6'
set firewall.@zone[2].input='REJECT'
set firewall.@zone[2].output='ACCEPT'
set firewall.@zone[2].forward='REJECT'
set firewall.@zone[2].masq='1'
set firewall.@zone[2].mtu_fix='1'

delete firewall.force_adblock_iot
set firewall.force_adblock_iot=redirect
set firewall.force_adblock_iot.name='Force-Adblock-Iot'
set firewall.force_adblock_iot.src='IoT'
add_list firewall.force_adblock_iot.proto='tcp'
add_list firewall.force_adblock_iot.proto='udp'
set firewall.force_adblock_iot.src_dport='53'
set firewall.force_adblock_iot.dest_port='53'
set firewall.force_adblock_iot.target='DNAT'
set firewall.force_adblock_iot.enabled='0'

delete firewall.force_adblock_lan
set firewall.force_adblock_lan=redirect
set firewall.force_adblock_lan.name='Force-Adblock-Lan'
set firewall.force_adblock_lan.src='lan'
add_list firewall.force_adblock_lan.proto='tcp'
add_list firewall.force_adblock_lan.proto='udp'
set firewall.force_adblock_lan.src_dport='53'
set firewall.force_adblock_lan.dest_port='53'
set firewall.force_adblock_lan.target='DNAT'
set firewall.force_adblock_lan.enabled='0'

delete firewall.@forwarding[2]
add firewall forwarding
set firewall.@forwarding[2]=forwarding
set firewall.@forwarding[2].src='lan'
set firewall.@forwarding[2].dest='IoT'

# Tailscale Zone
delete firewall.@zone[3]
add firewall zone
set firewall.@zone[3]=zone
set firewall.@zone[3].name='tailscale'
add_list firewall.@zone[3].network='tailscale'
add_list firewall.@zone[3].network='wan'
set firewall.@zone[3].input='ACCEPT'
set firewall.@zone[3].output='ACCEPT'
set firewall.@zone[3].forward='REJECT'
set firewall.@zone[3].masq='1'
set firewall.@zone[3].mtu_fix='1'
set firewall.@zone[3].masq6='1'

delete firewall.@forwarding[3]
add firewall forwarding
set firewall.@forwarding[3].src='tailscale'
set firewall.@forwarding[3].dest='lan'

delete firewall.@forwarding[4]
add firewall forwarding
set firewall.@forwarding[4].src='lan'
set firewall.@forwarding[4].dest='tailscale'

# ZeroTier Zone
delete firewall.@zone[4]
add firewall zone
set firewall.@zone[4]=zone
set firewall.@zone[4].name='zerotier'
add_list firewall.@zone[4].network='zerotier'
set firewall.@zone[4].input='ACCEPT'
set firewall.@zone[4].output='ACCEPT'
set firewall.@zone[4].forward='ACCEPT'
set firewall.@zone[4].masq='1'

delete firewall.@forwarding[5]
add firewall forwarding
set firewall.@forwarding[5].src='zerotier'
set firewall.@forwarding[5].dest='lan'

delete firewall.@forwarding[6]
add firewall forwarding
set firewall.@forwarding[6].src='zerotier'
set firewall.@forwarding[6].dest='wan'

delete firewall.@forwarding[7]
add firewall forwarding
set firewall.@forwarding[7].src='lan'
set firewall.@forwarding[7].dest='zerotier'

# NSS offloading
delete firewall.qcanssecm
set firewall.qcanssecm=include
set firewall.qcanssecm.type='script'
set firewall.qcanssecm.path='/etc/firewall.d/qca-nss-ecm'

commit firewall
EOF

uci -q batch <<'EOF'
### Here onwards are selective rules to open ports to the WAN side (outside)

# 1. Allow SSH
set firewall.allow_ssh_wan=rule
set firewall.allow_ssh_wan.name='Allow-SSH-WAN'
set firewall.allow_ssh_wan.src='wan'
set firewall.allow_ssh_wan.dest_port='22'
set firewall.allow_ssh_wan.target='ACCEPT'
set firewall.allow_ssh_wan.enabled='0'
uci -q delete firewall.allow_ssh_wan.proto
uci add_list firewall.allow_ssh_wan.proto='tcp'

# 2. Allow ttyd and btop via ttyd
set firewall.allow_ttyd_management_wan=rule
set firewall.allow_ttyd_management_wan.name='Allow-Ttyd-Management-WAN'
set firewall.allow_ttyd_management_wan.src='wan'
set firewall.allow_ttyd_management_wan.dest_port='7681'
set firewall.allow_ttyd_management_wan.target='ACCEPT'
set firewall.allow_ttyd_management_wan.enabled='0'
uci add_list firewall.allow_ttyd_management_wan.proto='tcp'

set firewall.allow_ttyd_btop_wan=rule
set firewall.allow_ttyd_btop_wan.name='Allow-Ttyd-Btop-WAN'
set firewall.allow_ttyd_btop_wan.src='wan'
set firewall.allow_ttyd_btop_wan.dest_port='7682'
set firewall.allow_ttyd_btop_wan.target='ACCEPT'
set firewall.allow_ttyd_btop_wan.enabled='0'
uci add_list firewall.allow_ttyd_btop_wan.proto='tcp'

# 3. Allow HTTP and HTTPS Management access
set firewall.allow_http_management_wan=rule
set firewall.allow_http_management_wan.name='Allow-HTTP-Management-WAN'
set firewall.allow_http_management_wan.src='wan'
set firewall.allow_http_management_wan.dest_port='80'
set firewall.allow_http_management_wan.target='ACCEPT'
set firewall.allow_http_management_wan.enabled='0'
uci -q delete firewall.allow_http_management_wan.proto
uci add_list firewall.allow_http_management_wan.proto='tcp'

set firewall.allow_https_management_wan=rule
set firewall.allow_https_management_wan.name='Allow-HTTPS-Management-WAN'
set firewall.allow_https_management_wan.src='wan'
set firewall.allow_https_management_wan.dest_port='443'
set firewall.allow_https_management_wan.target='ACCEPT'
set firewall.allow_https_management_wan.enabled='0'
uci -q delete firewall.allow_https_management_wan.proto
uci add_list firewall.allow_https_management_wan.proto='tcp'

# 4. Allow Avahi (Bonjour)
set firewall.allow_avahi_wan=rule
set firewall.allow_avahi_wan.name='Allow-Avahi-WAN'
set firewall.allow_avahi_wan.src='wan'
set firewall.allow_avahi_wan.dest_port='5353'
set firewall.allow_avahi_wan.target='ACCEPT'
set firewall.allow_avahi_wan.enabled='0'
uci -q delete firewall.allow_avahi_wan.proto
uci add_list firewall.allow_avahi_wan.proto='udp'

# 5. Allow SMB
set firewall.allow_smb_wan=rule
set firewall.allow_smb_wan.name='Allow-SMB-WAN'
set firewall.allow_smb_wan.src='wan'
set firewall.allow_smb_wan.dest_port='445'
set firewall.allow_smb_wan.target='ACCEPT'
set firewall.allow_smb_wan.enabled='0'
uci -q delete firewall.allow_smb_wan.proto
uci add_list firewall.allow_smb_wan.proto='tcp'

# 6. Allow Plex Media Server, discovery ports
set firewall.allow_plex_http_wan=rule
set firewall.allow_plex_http_wan.name='Allow-Plex-HTTP-WAN'
set firewall.allow_plex_http_wan.src='wan'
set firewall.allow_plex_http_wan.dest_port='32400'
set firewall.allow_plex_http_wan.target='ACCEPT'
set firewall.allow_plex_http_wan.enabled='0'
uci -q delete firewall.allow_plex_http_wan.proto
uci add_list firewall.allow_plex_http_wan.proto='tcp'

set firewall.allow_plex_discovery_wan=rule
set firewall.allow_plex_discovery_wan.name='Allow-Plex-Discovery-WAN'
set firewall.allow_plex_discovery_wan.src='wan'
set firewall.allow_plex_discovery_wan.dest_port='32410 32412 32413 32414'
set firewall.allow_plex_discovery_wan.target='ACCEPT'
set firewall.allow_plex_discovery_wan.enabled='0'
uci -q delete firewall.allow_plex_discovery_wan.proto
uci add_list firewall.allow_plex_discovery_wan.proto='udp'

# 7. Allow AriaNG
set firewall.allow_ariang_wan=rule
set firewall.allow_ariang_wan.name='Allow-AriaNG-WAN'
set firewall.allow_ariang_wan.src='wan'
set firewall.allow_ariang_wan.dest_port='6800'
set firewall.allow_ariang_wan.target='ACCEPT'
set firewall.allow_ariang_wan.enabled='0'
uci -q delete firewall.allow_ariang_wan.proto
uci add_list firewall.allow_ariang_wan.proto='tcp'
uci add_list firewall.allow_ariang_wan.proto='udp'

set firewall.allow_ariang_bittorrent_wan=rule
set firewall.allow_ariang_bittorrent_wan.name='Allow-AriaNG-BitTorrent-WAN'
set firewall.allow_ariang_bittorrent_wan.src='wan'
set firewall.allow_ariang_bittorrent_wan.dest_port='6881-6999'
set firewall.allow_ariang_bittorrent_wan.target='ACCEPT'
set firewall.allow_ariang_bittorrent_wan.enabled='0'
uci -q delete firewall.allow_ariang_bittorrent_wan.proto
uci add_list firewall.allow_ariang_bittorrent_wan.proto='tcp'
uci add_list firewall.allow_ariang_bittorrent_wan.proto='udp'

# 8. Allow MiniDLNA, discovery ports
set firewall.allow_minidlna_wan=rule
set firewall.allow_minidlna_wan.name='Allow-MiniDLNA-WAN'
set firewall.allow_minidlna_wan.src='wan'
set firewall.allow_minidlna_wan.dest_port='8200'
set firewall.allow_minidlna_wan.target='ACCEPT'
set firewall.allow_minidlna_wan.enabled='0'
uci -q delete firewall.allow_minidlna_wan.proto
uci add_list firewall.allow_minidlna_wan.proto='tcp'

set firewall.allow_minidlna_discovery_wan=rule
set firewall.allow_minidlna_discovery_wan.name='Allow-MiniDLNA-Discovery-WAN'
set firewall.allow_minidlna_discovery_wan.src='wan'
set firewall.allow_minidlna_discovery_wan.dest_port='1900'
set firewall.allow_minidlna_discovery_wan.target='ACCEPT'
set firewall.allow_minidlna_discovery_wan.enabled='0'
uci -q delete firewall.allow_minidlna_discovery_wan.proto
uci add_list firewall.allow_minidlna_discovery_wan.proto='udp'

commit firewall
EOF

fi

exit 0