#!/bin/sh

if /etc/has-no-defaults.sh tailscale; then

    touch /etc/config/tailscale

    uci -q batch <<'EOF'
delete tailscale.settings
add tailscale.settings
set tailscale.settings.log_stderr='1'
set tailscale.settings.log_stdout='0'
set tailscale.settings.port='41641'
set tailscale.settings.state_file='/etc/tailscale/tailscaled.state'
set tailscale.settings.fw_mode='nftables'
set tailscale.settings.enable='0'
set tailscale.settings.udp_gro_enable='0'

commit tailscale
EOF

fi

exit 0