#!/bin/sh

if /usr/bin/is-default-config umdns; then

    touch /etc/config/umdns

    uci -q batch <<'EOF'
delete umdns.@umdns[0]
add umdns umdns
set umdns.@umdns[0]=umdns
set umdns.@umdns[0].jail='1'
add_list umdns.@umdns[0].network='lan'
add_list umdns.@umdns[0].network='IoT'

commit umdns
EOF

fi

exit 0
