#!/bin/sh

if /usr/bin/is-default-config adblock; then

    touch /etc/config/adblock

    uci -q batch <<'EOF'
delete adblock.global
set adblock.global=adblock
set adblock.global.adb_enabled='0'
set adblock.global.adb_debug='0'
set adblock.global.adb_forcedns='1'
set adblock.global.adb_safesearch='0'
set adblock.global.adb_dnsfilereset='0'
set adblock.global.adb_mail='0'
set adblock.global.adb_report='0'
set adblock.global.adb_backup='1'
set adblock.global.adb_dns='unbound'
set adblock.global.adb_fetchutil='curl'
set adblock.global.adb_fetchcommand='curl'
set adblock.global.adb_dnsflush='1'
set adblock.global.adb_trigger_delay='60'
set adblock.global.adb_dnsforce='0'
set adblock.global.adb_nicelimit='0'
set adblock.global.adb_lookupdomain='gstatic.com'

add_list adblock.global.adb_trigger='wan'
add_list adblock.global.adb_zonelist='IoT'
add_list adblock.global.adb_zonelist='lan'

# List sources for new Adblock version
add_list adblock.adb_feed 'adguard'
add_list adblock.adb_feed 'adguard_tracking'
add_list adblock.adb_feed 'android_tracking'
add_list adblock.adb_feed 'anti_ad'
add_list adblock.adb_feed 'anudeep'
add_list adblock.adb_feed 'bitcoin'
add_list adblock.adb_feed 'disconnect'
add_list adblock.adb_feed 'firetv_tracking'
add_list adblock.adb_feed 'phishing_army'
add_list adblock.adb_feed 'smarttv_tracking'
add_list adblock.adb_feed 'spam404'
add_list adblock.adb_feed 'wally3k'
add_list adblock.adb_feed 'whocares'
add_list adblock.adb_feed 'winspy'
add_list adblock.adb_feed 'yoyo'

commit adblock
EOF

fi

exit 0
