#!/bin/sh

if /usr/bin/is-default-config aria2; then

    touch /etc/config/aria2

    uci -q batch <<'EOF'
delete adblock.main
set aria2.main.enabled='0'
set aria2.main.user='SMBUSER'
set aria2.main.group='SMBUSER'
set aria2.main.dir='/mnt/sda1/downloads'
set aria2.main.config_dir='/mnt/sda1/downloads/.aria2'

commit aria2
EOF

fi

exit 0