#!/bin/sh

if /usr/bin/is-default-config ksmbd; then

    touch /etc/config/ksmbd

    uci -q batch <<'EOF'
delete ksmbd.@globals[0]
add ksmbd globals
set ksmbd.@globals[0]=globals
set ksmbd.@globals[0].workgroup='WORKGROUP'
set ksmbd.@globals[0].interface='lan'
set ksmbd.@globals[0].description='OpenWrt_WRX36'

delete ksmbd.@share[0]
add ksmbd share
set ksmbd.@share[0]=share
set ksmbd.@share[0].read_only='no'
set ksmbd.@share[0].users='SMBUSER'
set ksmbd.@share[0].guest_ok='no'
set ksmbd.@share[0].create_mask='0666'
set ksmbd.@share[0].dir_mask='0777'

commit ksmbd
EOF

fi

exit 0
