#!/bin/sh

if /etc/has-no-defaults.sh plexmediaserver; then

    touch /etc/config/plexmediaserver

    uci -q batch <<'EOF'
delete plexmediaserver.main
add plexmediaserver.main
set plexmediaserver.main.plex_browser_root='/mnt/sda1/Media'
set plexmediaserver.main.plex_drive_mnt='/mnt/sda1'
set plexmediaserver.main.plex_drive_dev='/dev/sda1'
set plexmediaserver.main.plex_library_dir='/mnt/sda1/Media/.plex/Library'
set plexmediaserver.main.plex_tmp_dir='/tmp/plexmediaserver'
set plexmediaserver.main.plex_application_support_dir='/mnt/sda1/Media/.plex/Library/Application Support'
set plexmediaserver.main.plex_compressed_archive_path='/mnt/sda1/Media/.plex/Library/Application/plexmediaserver.sqfs'
set plexmediaserver.main.plex_version=''
set plexmediaserver.main.plex_bin_dir=''
set plexmediaserver.main.enabled='0'

commit plexmediaserver
EOF

fi

exit 0