#!/bin/sh

# ------------------------------------------------------------------
# Disable and stop selected services
# ------------------------------------------------------------------

# All these services require configuration, except for sysntpd (the
# system native NTP Client) because we're using chrony instead.
# Also, these makes the server not boot-loop if the conf is bad
SERVICES="
plexmediaserver
zerotier
tailscale
ddns
banip
sysntpd
minidlna
watchcat
netdata
smp_affinity_vpn
"

for service in $SERVICES; do
  # shellcheck disable=SC2086
  if [ -f /etc/init.d/$service ]; then
    /etc/init.d/$service disable
  fi
done

# Additional check: if the it-tools file does not exist, also disable it
if [ ! -f /srv/it-tools.squashfs ] && [ -f /etc/init.d/it-tools ]; then
  /etc/init.d/it-tools disable
else
  /etc/init.d/it-tools enable
fi
exit 0