#!/bin/sh

# ------------------------------------------------------------------
# Disable and stop selected services
# ------------------------------------------------------------------

# All these services require configuration, except for sysntpd (the
# system native NTP Client) because we're using chrony instead.
# Also, these makes the server not boot-loop if the conf is bad
SERVICES="
plexmediaserver
zerotier
tailscale
ddns
banip
sysntpd
minidlna
watchcat
netdata
smp_affinity_vpn
"

for service in $SERVICES; do
  # shellcheck disable=SC2086
  if [ -f /etc/init.d/$service ]; then
    /etc/init.d/$service disable
  fi
done

exit 0