#!/bin/sh

# Add avahi group and user with the ID 105
if [ -f /etc/init.d/avahi-daemon ]; then
    # Check if group 'avahi' exists, if not add it
    if ! grep -q "^avahi:" /etc/group; then
        echo "avahi:x:105:" >> /etc/group
    fi

    # Check if user 'avahi' exists, if not add it
    if ! grep -q "^avahi:" /etc/passwd; then
        echo "avahi:*:105:105:avahi:/var/run/avahi-daemon:/bin/false" >> /etc/passwd
    fi

    /etc/init.d/avahi-daemon restart
fi

exit 0