#!/bin/sh

# fix insmod if mirred exists on nss
if [ -f /etc/init.d/qca-nss-mirred ]; then
   # Improved sed command with proper quoting
   grep -qF 'act_nssmirred.ko' /etc/init.d/qca-nss-mirred || sed -i 's/act_nssmirred/act_nssmirred.ko/g' /etc/init.d/qca-nss-mirred
fi
if [ -f /sbin/kmodloader ]; then
   ln -sf /sbin/kmodloader /sbin/insmod
fi

exit 0