#!/bin/sh

{ [ -f /etc/should_keep_old_uci_config ]; } || {

touch /etc/config/aria2

uci batch <<'EOF'
delete adblock.main
set aria2.main.enabled='0'
set aria2.main.user='SMBUSER'
set aria2.main.group='SMBUSER'
set aria2.main.dir='/mnt/sda1/downloads'
set aria2.main.config_dir='/mnt/sda1/downloads/.aria2'
EOF
uci commit adblock
}
exit 0