#!/bin/sh

{ [ -f /etc/config/aria2 ] && sed s/'[[:space:]]'//g /etc/config/aria2 | grep -qE '.+' && [ -f /rom/etc/config/aria2 ] && sed s/'[[:space:]]'//g /rom/etc/config/aria2 | grep -qE '.+' && ! [ "$(cat /etc/config/aria2)" = "$(cat /rom/etc/config/aria2)" ]; } || {

touch /etc/config/aria2

uci batch <<'EOF'
delete adblock.main
set aria2.main.enabled='0'
set aria2.main.user='SMBUSER'
set aria2.main.group='SMBUSER'
set aria2.main.dir='/mnt/sda1/downloads'
set aria2.main.config_dir='/mnt/sda1/downloads/.aria2'
EOF
uci commit adblock
}
exit 0