#!/bin/sh

{ [ -f /etc/config/plexmediaserver ] && sed s/'[[:space:]]'//g /etc/config/plexmediaserver | grep -qE '.+' && [ -f /rom/etc/config/plexmediaserver ] && sed s/'[[:space:]]'//g /rom/etc/config/plexmediaserver | grep -qE '.+' && ! [ "$(cat /etc/config/plexmediaserver)" = "$(cat /rom/etc/config/plexmediaserver)" ]; } || {

touch /etc/config/plexmediaserver

}
exit 0