#!/bin/sh

{ [ -f /etc/config/system ] && sed s/'[[:space:]]'//g /etc/config/system | grep -qE '.+' && [ -f /rom/etc/config/system ] && sed s/'[[:space:]]'//g /rom/etc/config/system | grep -qE '.+' && ! [ "$(cat /etc/config/system)" = "$(cat /rom/etc/config/system)" ]; } || {

touch /etc/config/system

uci batch <<'EOF'
delete system.@system[0]
add system system
set system.@system[0]=system
set system.@system[0].hostname='OpenWrt_WRX36'
set system.@system[0].ttylogin='0'
set system.@system[0].log_size='64'
set system.@system[0].urandom_seed='0'
set system.@system[0].log_proto='udp'
set system.@system[0].conloglevel='8'
set system.@system[0].cronloglevel='5'
set system.@system[0].zram_comp_algo='zstd'
set system.@system[0].description='OpenWrt on Dynalink DL-WRX36 (NSS)'
set system.@system[0].notes='Custom NSS-enabled OpenWrt firmware for Dynalink DL-WRX36'

delete system.ntp
set system.ntp=timeserver
set system.ntp.enabled='0'

# --- LED Configuration ---
# Hardware paths identified via ssh: /sys/class/leds/90000.mdio-1:1c:*

delete system.led_wan_green
delete system.led_wan_port_green
set system.led_wan_green=led
set system.led_wan_green.name='WAN-PORT-LINK-GREEN'
# Exact sysfs path found on device:
set system.led_wan_green.sysfs='90000.mdio-1:1c:green:wan'
set system.led_wan_green.trigger='netdev'
set system.led_wan_green.dev='wan'
set system.led_wan_green.mode='link'

delete system.led_wan_yellow
delete system.led_wan_port_green
set system.led_wan_yellow=led
set system.led_wan_yellow.name='WAN-PORT-LINK-YELLOW'
# Exact sysfs path found on device:
set system.led_wan_yellow.sysfs='90000.mdio-1:1c:yellow:wan'
set system.led_wan_yellow.trigger='netdev'
set system.led_wan_yellow.dev='wan'
set system.led_wan_yellow.mode='tx rx'

delete system.@rngd[0]
add system rngd
set system.@rngd[0]=rngd
set system.@rngd[0].enabled='1'
set system.@rngd[0].device='/dev/urandom'
EOF
uci commit system
}
exit 0