#!/bin/sh

if /etc/has-no-defaults.sh usteer; then

    touch /etc/config/usteer

    uci -q batch <<'EOF'
delete usteer.@usteer[0]
add usteer usteer
set usteer.@usteer[0]=usteer
set usteer.@usteer[0].network='lan'
set usteer.@usteer[0].syslog='1'
set usteer.@usteer[0].local_mode='1'
set usteer.@usteer[0].ipv6='0'
set usteer.@usteer[0].debug_level='2'
set usteer.@usteer[0].band_steering_threshold='1'
set usteer.@usteer[0].band_steering_interval='30000'
set usteer.@usteer[0].link_measurement_interval='30000'
set usteer.@usteer[0].ssid_list='OpenWrt_WiFi'
set usteer.@usteer[0].band_steering_min_snr='0'

commit usteer
EOF

fi

exit 0
