#!/bin/sh /etc/rc.common

# Start before Unbound
START=18

UNBOUND_PATH=/var/lib/unbound

start() {
    # 1. Ensure the unbound directory exists (it is often in tmpfs)
    if [ ! -d "$UNBOUND_PATH" ]; then
        mkdir -p $UNBOUND_PATH
    fi

    # Set permissions so the unbound user can access the unbound working directory.
    chown unbound:unbound $UNBOUND_PATH
    chmod 755 $UNBOUND_PATH

    # 2. Copy the certificate bundle to the chroot location expected by unbound_srv.conf if it does not exists
    if [ -f /etc/ssl/certs/ca-certificates.crt ] && [ ! -f $UNBOUND_PATH/ca-certificates.crt ]; then
        cp /etc/ssl/certs/ca-certificates.crt $UNBOUND_PATH/ca-certificates.crt
    fi

    # Ensure the file is readable by the unbound user
    chmod 644 $UNBOUND_PATH/ca-certificates.crt

    # 3. Only copy root.key if it exists (it might not if we skipped anchor)
    if [ -f /etc/unbound/root.key ] && [ ! -f $UNBOUND_PATH/root.key ]; then
        cp -p /etc/unbound/root.key $UNBOUND_PATH/root.key
    fi

    # Ensure the file is readable by the unbound user
    chmod 644 $UNBOUND_PATH/root.key
}
