#!/bin/sh
SOCKET="/tmp/ttyd_btop.sock"
export XDG_CONFIG_HOME=/etc/btop-config

# 1. Restore Environment Variables
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
export TERM=xterm-256color

# 2. Force tmux settings (Shell + Title Fix)
TMUX_CONF="/tmp/tmux_btop.conf"
{
    # Force the shell to /bin/sh to prevent crashes
    echo "set-option -g default-shell /bin/sh"
} > "$TMUX_CONF"

# 3. If attach failed, create a new one
if ! /usr/bin/tmux -S "$SOCKET" -f "$TMUX_CONF" -u -2 attach-session -t system_stats 2>/dev/null; then
    rm -f "$SOCKET"
    exec /usr/bin/tmux -S "$SOCKET" -f "$TMUX_CONF" -u -2 \
         new-session -s system_stats '/usr/bin/btop --force-utf' \; \
         set-option -g destroy-unattached on
fi