#!/bin/sh

# Only run if the interface is 'wan' and the action is 'ifup'
[ "$INTERFACE" = "wan" ] || exit 0
[ "$ACTION" = "ifup" ] || exit 0

# Check if the tool exists and runs it
if [ -x /usr/sbin/chrony-hotplug ] && /usr/bin/has-internet; then
    logger -t chrony-hotplug "Interface $INTERFACE is up and connected to the Internet. Triggering time sync..."
    /usr/sbin/chrony-hotplug
else
    logger -t chrony-hotplug "Interface $INTERFACE is up but not connected to Internet. Aborting time sync..."
fi