#!/bin/sh

# Only run if the interface is 'wan' and the action is 'ifup'
[ "$INTERFACE" = "wan" ] || exit 0
[ "$ACTION" = "ifup" ] || exit 0

# Load Unbound defaults to get file paths ($UB_RKEY_FILE, $UB_ANCHOR)
. /usr/lib/unbound/defaults.sh

# Run the logic in the background to avoid blocking the hotplug system
(
    # Wait for actual internet connectivity (try for 60 seconds)
    count=0
    while [ $count -lt 12 ]; do
        # Ping check to ensure we can reach the outside world
        if ping -q -c 1 -W 5 8.8.8.8 >/dev/null 2>&1; then
            logger -t unbound-anchor-and-hints "Internet connection detected. Validating Root Trust Anchor..."

            DOWNLOADED=false

            # download the hints if these do not exist.
            if [ ! -s "$UB_RHINT_FILE" ]; then
                curl -o "$UB_RHINT_FILE" "https://www.internic.net/domain/named.cache"

                chown unbound:unbound "$UB_RHINT_FILE"
                logger -t unbound-anchor-and-hints "Hints downloaded"

                DOWNLOADED=true
            fi

            # Execute the anchor maintenance
            if [ -x "$UB_ANCHOR" ]; then
                # -a attempts to update/verify the root key
                $UB_ANCHOR -a "$UB_RKEY_FILE"
                
                chown unbound:unbound "$UB_RKEY_FILE"

                DOWNLOADED=true
            fi

            if [ "$DOWNLOADED" = true ]; then
                logger -t unbound-anchor "Restarting Unbound..."
                break
            fi

        fi
        
        # Wait 5 seconds before retrying
        sleep 5
        count=$((count+1))
    done
) &

exit 0